{!! HTML::script('admin/vendor/jquery/dist/jquery.min.js') !!}
{!! HTML::script('admin/vendor/bootstrap/dist/js/bootstrap.min.js') !!}
{!! HTML::script('admin/vendor/metisMenu/dist/metisMenu.min.js') !!}
{!! HTML::script('admin/vendor/datatables/media/js/jquery.dataTables.min.js') !!}
{!! HTML::script('admin/vendor/datatables-plugins/integration/bootstrap/3/dataTables.bootstrap.min.js') !!}
{!! HTML::script('admin/vendor/dist/js/sb-admin-2.js') !!}
{!! HTML::script('admin/js/admin.js') !!}
{!! HTML::script('admin/vendor/ckeditor/ckeditor.js') !!}
{!! HTML::script('admin/vendor/ckeditor/config.js') !!}
{!! HTML::script('admin/vendor/ckeditor/lang/en.js') !!}
{!! HTML::script('admin/vendor/ckeditor/styles.js') !!}