@extends('layouts.main')

{{-- Remove slider --}}
@section('slider')
@overwrite

@section('main-content')
    <section id="content" class="container clearfix">
		@include('layouts.partial.sidebar')
		<section id="main" class="three-fourths column-last">
            <p>Integer lacinia luctus euismod. Donec tristique dapibus tellus ut lobortis. Fusce mollis eros in nunc auctor sit amet imperdiet nisl imperdiet. Donec varius mauris ac urna condimentum ultrices. Vestibulum tempus vehicula dolor id fermentum. Phasellus suscipit nisi eu mi tincidunt ultrices. Phasellus a libero id massa suscipit pellentesque in sed urna. Proin quis convallis ligula. Donec adipiscing volutpat urna, vitae fringilla nibh pretium at. In tincidunt convallis mi, non tempor ante bibendum rutrum. Aenean eget felis tellus. Praesent tellus metus, viverra vitae pellentesque id, consectetur id magna. Sed pellentesque suscipit imperdiet. Mauris blandit eros eu orci volutpat et dictum nunc fermentum. Donec nisl tortor, semper ac porttitor eget, pellentesque placerat metus. Duis mollis pellentesque nisl eu dignissim.</p>
            <p>Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Quisque suscipit, lorem in ornare fermentum, neque sapien scelerisque diam, consectetur suscipit dolor odio at nibh. Donec pretium orci eu dolor laoreet in mattis purus aliquam. Pellentesque ut libero vitae lacus scelerisque scelerisque. Curabitur ultricies, tellus bibendum egestas aliquet, nulla justo malesuada metus, sit amet tempus lorem augue a ante. Duis quis nisl lectus, sit amet dignissim nulla. Phasellus neque nisi, convallis varius tempor non, sodales at ante. Vivamus sapien risus, fermentum quis congue eu, tempus non mi. Praesent porttitor, orci quis semper laoreet, tortor nisl imperdiet turpis, ut posuere dolor est et mauris. Sed ut sem massa, id malesuada purus.</p>
            <p>Pellentesque aliquet erat dui, commodo interdum erat. Vivamus non metus in metus commodo sodales. Integer commodo sapien vitae erat eleifend lacinia. Sed vitae pulvinar tortor. Ut tempor arcu eget eros convallis ac tincidunt urna hendrerit. Integer ac dolor urna, in porta mauris. Nullam iaculis nibh dolor, nec blandit magna. Maecenas ultricies venenatis diam, eget accumsan dui fringilla eu. Nam tempor eros id tellus laoreet tempus. Curabitur interdum ligula vel est sagittis tincidunt. Suspendisse potenti. Suspendisse lacinia, risus et dictum pharetra, ante risus condimentum magna, eu rutrum erat nisi vitae magna.</p>
            <p>Quisque elementum, leo sed congue suscipit, lacus neque commodo massa, sit amet dictum mauris justo sed magna. Donec imperdiet risus id odio eleifend nec imperdiet elit porta. Mauris imperdiet augue ac erat sollicitudin aliquam. In id nisl ligula, et consequat ante. Nullam faucibus bibendum neque quis auctor. Nullam lobortis, nisi in volutpat eleifend, nibh neque fringilla orci, et luctus sapien dolor nec leo. Morbi non vestibulum nulla. Vivamus pellentesque sollicitudin justo ac varius. Nullam a nunc tellus, ac consequat eros. Nullam turpis libero, vestibulum nec fermentum in, vestibulum nec ipsum. Sed rutrum lacus cursus dui consequat fermentum convallis sapien tempus. Vestibulum tincidunt elit sed nibh pharetra et consectetur leo laoreet. Aliquam ut urna id est dapibus semper vitae ut odio. Nullam sit amet orci nec velit commodo mollis. In hac habitasse platea dictumst. Nullam tempus, metus non venenatis fringilla, nisi risus consequat quam, nec suscipit justo dolor ut felis.</p>
        </section>
    </section>
    
@stop